# Generated by Django 4.1.7 on 2023-03-14 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestatus',
            old_name='name',
            new_name='status',
        ),
        migrations.AddField(
            model_name='case',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casestatus',
            name='case',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='remanage.case'),
        ),
        migrations.AddField(
            model_name='casestatus',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
