# Generated by Django 4.1.7 on 2023-03-24 22:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('role', models.CharField(choices=[('SV', 'Sinh viên'), ('GV', 'Giảng viên'), ('PB', 'Phòng ban')], max_length=2)),
            ],
        ),
    ]
