# Generated by Django 4.1.7 on 2023-03-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0002_customuser_customer_managecntt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managecntt',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='ManageCNTT',
        ),
    ]
