# Generated by Django 4.1.7 on 2023-03-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0008_userprofile_fullname_alter_userprofile_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fullname',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(max_length=10),
        ),
    ]
