# Generated by Django 4.1.7 on 2023-03-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0010_topicsubmission_mytopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mytopic',
            name='status',
            field=models.CharField(default='Chờ tiếp nhận', max_length=20),
        ),
    ]
