# Generated by Django 4.1.7 on 2023-03-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0010_image_topic_image_alter_topic_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/topic'),
        ),
    ]
