# Generated by Django 4.1.7 on 2023-03-27 14:59

from django.db import migrations, models
import topicyeucau.models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0012_alter_topic_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/topic')),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=topicyeucau.models.Image),
        ),
    ]
