# Generated by Django 4.1.7 on 2023-03-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0011_alter_topic_image'),
        ('topicyeucau', '0014_alter_topic_image'),
    ]

    operations = [
    ]
