# Generated by Django 4.1.7 on 2023-03-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0015_merge_0011_alter_topic_image_0014_alter_topic_image'),
        ('topicyeucau', '0016_auto_20230327_2337'),
    ]

    operations = [
    ]
