# Generated by Django 4.1.7 on 2023-03-27 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0017_merge_20230327_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
