# Generated by Django 4.1.7 on 2023-03-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0018_topic_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cus_id',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
