# Generated by Django 4.1.7 on 2023-04-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0020_mytopic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytopic',
            name='start_time_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
