# Generated by Django 4.1.7 on 2023-04-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0025_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
