# Generated by Django 4.1.7 on 2023-04-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0027_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytopic',
            name='user',
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mytopic',
            name='cus_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='mytopic',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
