# Generated by Django 4.2 on 2023-05-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0038_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='role',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(default='default_category', max_length=255),
        ),
        migrations.AlterField(
            model_name='mytopic',
            name='status',
            field=models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Hoàn thành', 'Hoàn thành')], default='Chờ tiếp nhận', max_length=20),
        ),
    ]
