# Generated by Django 4.2 on 2023-05-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0041_image_request_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='request_count',
        ),
        migrations.AddField(
            model_name='category',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
    ]
