# Generated by Django 4.2 on 2023-05-03 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0042_remove_image_request_count_category_request_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='topicyeucau.userprofile'),
        ),
    ]
