# Generated by Django 4.2 on 2023-05-03 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0043_topic_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='topic',
            name='author_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='topicyeucau.userprofile'),
        ),
    ]
