# Generated by Django 4.2 on 2023-05-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0044_remove_topic_user_profile_topic_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytopic',
            name='author_role',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
