# Generated by Django 4.2 on 2023-05-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0045_mytopic_author_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytopic',
            name='author_role',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='author_profile',
        ),
    ]
