# Generated by Django 4.2 on 2023-05-04 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0046_remove_mytopic_author_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytopic',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topicyeucau.userprofile'),
        ),
    ]
