# Generated by Django 4.2 on 2023-05-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0047_mytopic_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytopic',
            name='user_profile',
        ),
    ]
