# Generated by Django 4.2 on 2023-05-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0048_remove_mytopic_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytopic',
            name='elapsed_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
