# Generated by Django 4.2 on 2023-05-04 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0051_remove_mytopic_name_mytopic_employee_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytopic',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
