# Generated by Django 4.2 on 2023-05-05 00:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0053_alter_mytopic_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicyeucau.topic')),
            ],
        ),
    ]
