# Generated by Django 4.2 on 2023-05-05 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0054_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytopic',
            name='rating',
        ),
    ]
