# Generated by Django 4.2 on 2023-05-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0059_article_category_alter_knowledge_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='article',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
