# Generated by Django 4.2 on 2023-05-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0060_remove_knowledge_article_knowledge_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
