# Generated by Django 4.2 on 2023-05-09 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topicyeucau', '0062_orderprocess_mytopic_order_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderprocess',
            options={},
        ),
        migrations.AddField(
            model_name='orderprocess',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
