# Generated by Django 4.2 on 2023-05-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0064_alter_orderprocess_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytopic',
            name='order_process',
        ),
        migrations.DeleteModel(
            name='OrderProcess',
        ),
    ]
