# Generated by Django 4.2 on 2023-05-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0065_remove_mytopic_order_process_delete_orderprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytopic',
            name='start_time_employee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
