# Generated by Django 4.2 on 2023-05-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0066_mytopic_start_time_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='tags',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/knowledge'),
        ),
    ]
