# Generated by Django 4.2.1 on 2023-05-15 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0069_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topicyeucau.knowledge'),
        ),
    ]
