# Generated by Django 4.2.1 on 2023-05-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0070_article_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
