# Generated by Django 4.2.1 on 2023-05-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicyeucau', '0071_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
